[package]
name = "bog"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
lol_html = "2.7.0"
maud = { version = "0.27", features = ["poem"] }
poem = { version = "3", features = ["static-files", "chrono", "cookie"] }
rand = "0.9"
rusqlite = { version = "0.37.0", features = ["chrono", "bundled"] }
rusqlite_migration = "2.3.0"
serde = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "process"] }
atom_syndication = "0.12"
tempfile = "3.23.0"
serde_json = "1.0.145"

[build-dependencies]
vergen-git2 = { version = "1", features = ["build", "cargo", "rustc", "si"] }
