[package]
name = "bog"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
maud = { version = "0.27", features = ["poem"] }
poem = { version = "3", features = ["static-files", "chrono"] }
rand = "0.9"
rusqlite = { version = "0.37.0", features = ["chrono"] }
rusqlite_migration = "2.3.0"
serde = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
vergen-git2 = { version = "1", features = ["build", "cargo", "rustc", "si"] }

